apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-ic-kustomization
resources:
  - secret-server.yaml
  - namespaces.yaml
  - all_attributes.yaml
  - generator-direct.yaml
  - api-gateway.yaml
  - frontend-namespace-via-apigw.yaml
  - virtualserverroute.yaml
  - virtualserver.yaml
