apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-ic-kustomization
resources:
  - ns-and-sa.yaml
  - rbac.yaml
  - default-server-secret.yaml
  - nginx-config.yaml
  - ingress-class.yaml
  - k8s.nginx.org_virtualservers.yaml
  - k8s.nginx.org_virtualserverroutes.yaml
  - k8s.nginx.org_transportservers.yaml
  - k8s.nginx.org_policies.yaml
  - daemon-nginx-plus.yaml
  - loadbalancer-aws-elb.yaml
